# Generated by Django 4.2 on 2024-03-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.domaine')),
            ],
        ),
    ]
