# Generated by Django 4.2 on 2024-03-01 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_branche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qcm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.JSONField()),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branche')),
            ],
        ),
    ]
