# Generated by Django 4.2 on 2024-03-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_qcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcm',
            name='plusieurChoix',
            field=models.BooleanField(default=False),
        ),
    ]
