# Generated by Django 5.0.3 on 2024-03-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_qcm_plusieurchoix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcm',
            old_name='reponse',
            new_name='propositions',
        ),
    ]
