# Generated by Django 4.2 on 2024-05-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_qcm_plusieurchoix_alter_branche_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branche',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='main.domaine'),
        ),
        migrations.AlterField(
            model_name='qcm',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='main.branche'),
        ),
    ]
